import os
import urllib.request
import boto3

def save_to_cloud(task_id: str, file_source: str):
    """
    Uploads a video to S3 / Cloudflare R2.
    `file_source` can be either a remote HTTP URL or a local file path.
    """
    local_path = f"/tmp/{task_id}.mp4"
    
    # 1. Handle downloading if source is a URL, or copying/using directly if local
    if file_source.startswith("http://") or file_source.startswith("https://"):
        urllib.request.urlretrieve(file_source, local_path)
    else:
        # It's already a local file path generated by Playwright
        local_path = file_source

    # 2. Upload to S3 / Cloudflare R2
    s3_client = boto3.client(
        's3',
        endpoint_url=os.getenv("S3_ENDPOINT_URL"),
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        region_name=os.getenv("AWS_REGION", "us-east-1")
    )
    
    bucket_name = os.getenv("S3_BUCKET_NAME", "seedance-videos")
    cloud_filename = f"{task_id}.mp4"
    
    s3_client.upload_file(local_path, bucket_name, cloud_filename)
    
    # 3. Clean up local temp file
    if os.path.exists(local_path):
        os.remove(local_path)
        
    print(f"📦 Successfully stored {cloud_filename} in {bucket_name}")
